'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServiceReference1
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CompositeType", [Namespace]:="http://schemas.datacontract.org/2004/07/WCFServiceWebRole1"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CompositeType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BoolValueField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StringValueField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BoolValue() As Boolean
            Get
                Return Me.BoolValueField
            End Get
            Set
                If (Me.BoolValueField.Equals(value) <> true) Then
                    Me.BoolValueField = value
                    Me.RaisePropertyChanged("BoolValue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StringValue() As String
            Get
                Return Me.StringValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StringValueField, value) <> true) Then
                    Me.StringValueField = value
                    Me.RaisePropertyChanged("StringValue")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.IService1")>  _
    Public Interface IService1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetData", ReplyAction:="http://tempuri.org/IService1/GetDataResponse")>  _
        Function GetData(ByVal value As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetData", ReplyAction:="http://tempuri.org/IService1/GetDataResponse")>  _
        Function GetDataAsync(ByVal value As Integer) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction:="http://tempuri.org/IService1/GetDataUsingDataContractResponse")>  _
        Function GetDataUsingDataContract(ByVal composite As ServiceReference1.CompositeType) As ServiceReference1.CompositeType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction:="http://tempuri.org/IService1/GetDataUsingDataContractResponse")>  _
        Function GetDataUsingDataContractAsync(ByVal composite As ServiceReference1.CompositeType) As System.Threading.Tasks.Task(Of ServiceReference1.CompositeType)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/getReports単純なサンプル", ReplyAction:="http://tempuri.org/IService1/getReports単純なサンプルResponse")>  _
        Function getReports単純なサンプル() As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/getReports単純なサンプル", ReplyAction:="http://tempuri.org/IService1/getReports単純なサンプルResponse")>  _
        Function getReports単純なサンプルAsync() As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/getReports10の倍数", ReplyAction:="http://tempuri.org/IService1/getReports10の倍数Response")>  _
        Function getReports10の倍数() As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/getReports10の倍数", ReplyAction:="http://tempuri.org/IService1/getReports10の倍数Response")>  _
        Function getReports10の倍数Async() As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/getReports見積書", ReplyAction:="http://tempuri.org/IService1/getReports見積書Response")>  _
        Function getReports見積書() As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/getReports見積書", ReplyAction:="http://tempuri.org/IService1/getReports見積書Response")>  _
        Function getReports見積書Async() As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/getReports郵便番号", ReplyAction:="http://tempuri.org/IService1/getReports郵便番号Response")>  _
        Function getReports郵便番号() As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/getReports郵便番号", ReplyAction:="http://tempuri.org/IService1/getReports郵便番号Response")>  _
        Function getReports郵便番号Async() As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/getReports広告", ReplyAction:="http://tempuri.org/IService1/getReports広告Response")>  _
        Function getReports広告() As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/getReports広告", ReplyAction:="http://tempuri.org/IService1/getReports広告Response")>  _
        Function getReports広告Async() As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/getReports請求書", ReplyAction:="http://tempuri.org/IService1/getReports請求書Response")>  _
        Function getReports請求書() As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/getReports請求書", ReplyAction:="http://tempuri.org/IService1/getReports請求書Response")>  _
        Function getReports請求書Async() As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/getReports商品一覧", ReplyAction:="http://tempuri.org/IService1/getReports商品一覧Response")>  _
        Function getReports商品一覧() As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/getReports商品一覧", ReplyAction:="http://tempuri.org/IService1/getReports商品一覧Response")>  _
        Function getReports商品一覧Async() As System.Threading.Tasks.Task(Of Byte())
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IService1Channel
        Inherits ServiceReference1.IService1, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Service1Client
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.IService1)
        Implements ServiceReference1.IService1
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetData(ByVal value As Integer) As String Implements ServiceReference1.IService1.GetData
            Return MyBase.Channel.GetData(value)
        End Function
        
        Public Function GetDataAsync(ByVal value As Integer) As System.Threading.Tasks.Task(Of String) Implements ServiceReference1.IService1.GetDataAsync
            Return MyBase.Channel.GetDataAsync(value)
        End Function
        
        Public Function GetDataUsingDataContract(ByVal composite As ServiceReference1.CompositeType) As ServiceReference1.CompositeType Implements ServiceReference1.IService1.GetDataUsingDataContract
            Return MyBase.Channel.GetDataUsingDataContract(composite)
        End Function
        
        Public Function GetDataUsingDataContractAsync(ByVal composite As ServiceReference1.CompositeType) As System.Threading.Tasks.Task(Of ServiceReference1.CompositeType) Implements ServiceReference1.IService1.GetDataUsingDataContractAsync
            Return MyBase.Channel.GetDataUsingDataContractAsync(composite)
        End Function
        
        Public Function getReports単純なサンプル() As Byte() Implements ServiceReference1.IService1.getReports単純なサンプル
            Return MyBase.Channel.getReports単純なサンプル
        End Function
        
        Public Function getReports単純なサンプルAsync() As System.Threading.Tasks.Task(Of Byte()) Implements ServiceReference1.IService1.getReports単純なサンプルAsync
            Return MyBase.Channel.getReports単純なサンプルAsync
        End Function
        
        Public Function getReports10の倍数() As Byte() Implements ServiceReference1.IService1.getReports10の倍数
            Return MyBase.Channel.getReports10の倍数
        End Function
        
        Public Function getReports10の倍数Async() As System.Threading.Tasks.Task(Of Byte()) Implements ServiceReference1.IService1.getReports10の倍数Async
            Return MyBase.Channel.getReports10の倍数Async
        End Function
        
        Public Function getReports見積書() As Byte() Implements ServiceReference1.IService1.getReports見積書
            Return MyBase.Channel.getReports見積書
        End Function
        
        Public Function getReports見積書Async() As System.Threading.Tasks.Task(Of Byte()) Implements ServiceReference1.IService1.getReports見積書Async
            Return MyBase.Channel.getReports見積書Async
        End Function
        
        Public Function getReports郵便番号() As Byte() Implements ServiceReference1.IService1.getReports郵便番号
            Return MyBase.Channel.getReports郵便番号
        End Function
        
        Public Function getReports郵便番号Async() As System.Threading.Tasks.Task(Of Byte()) Implements ServiceReference1.IService1.getReports郵便番号Async
            Return MyBase.Channel.getReports郵便番号Async
        End Function
        
        Public Function getReports広告() As Byte() Implements ServiceReference1.IService1.getReports広告
            Return MyBase.Channel.getReports広告
        End Function
        
        Public Function getReports広告Async() As System.Threading.Tasks.Task(Of Byte()) Implements ServiceReference1.IService1.getReports広告Async
            Return MyBase.Channel.getReports広告Async
        End Function
        
        Public Function getReports請求書() As Byte() Implements ServiceReference1.IService1.getReports請求書
            Return MyBase.Channel.getReports請求書
        End Function
        
        Public Function getReports請求書Async() As System.Threading.Tasks.Task(Of Byte()) Implements ServiceReference1.IService1.getReports請求書Async
            Return MyBase.Channel.getReports請求書Async
        End Function
        
        Public Function getReports商品一覧() As Byte() Implements ServiceReference1.IService1.getReports商品一覧
            Return MyBase.Channel.getReports商品一覧
        End Function
        
        Public Function getReports商品一覧Async() As System.Threading.Tasks.Task(Of Byte()) Implements ServiceReference1.IService1.getReports商品一覧Async
            Return MyBase.Channel.getReports商品一覧Async
        End Function
    End Class
End Namespace
